# Generated by Django 4.2.5 on 2023-09-20 10:41

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("books", "0002_alter_book_description"),
    ]

    operations = [
        migrations.RenameModel(old_name="Comments", new_name="Comment",),
    ]
