# Generated by Django 4.2.5 on 2023-10-04 03:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("books", "0003_rename_comments_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="upload_by",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="book", name="author", field=models.CharField(max_length=150),
        ),
    ]
