# Generated by Django 4.2.5 on 2023-10-09 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0004_book_upload_by_alter_book_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="genre",
            field=models.ManyToManyField(default=None, to="books.category"),
        ),
    ]
