# Generated by Django 4.2.5 on 2023-10-10 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0006_alter_book_upload_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="genre",
            field=models.ManyToManyField(blank=True, default=None, to="books.category"),
        ),
    ]
