# Generated by Django 4.2.5 on 2023-10-11 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0007_alter_book_genre"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="genre",
            field=models.ManyToManyField(default=None, to="books.category"),
        ),
    ]
