# Generated by Django 4.2.5 on 2023-09-20 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="profile", name="first_name",),
        migrations.RemoveField(model_name="profile", name="last_name",),
    ]
